function saveNew( fg, name, dims, ax_dims)
if nargin < 3 
    set(fg,'Position',[100 100 900 300]);
    set(fg,'PaperOrientation','portrait', ...
        'PaperSize',[9 3], ...
        'PaperPositionMode', 'auto', ...
        'PaperType','<custom>');
    saveas(fg,[name '.png'], 'png')
elseif nargin < 4 
    set(fg,'Position',[100 100 dims]);
    set(fg,'PaperOrientation','portrait', ...
        'PaperSize', dims/100, ...
        'PaperPositionMode', 'auto', ...
        'PaperType','<custom>');
    saveas(fg,[name '.png'], 'png')  
else 
    set(fg,'Position',[100 100 dims]);
    set(fg,'PaperOrientation','portrait', ...
        'PaperSize', dims/100, ...
        'PaperPositionMode', 'auto', ...
        'PaperType','<custom>');
    set(gca,'position',ax_dims)
    saveas(fg,[name '.png'], 'png')    
end
end