function display_At()
global file
global gui_Tr
global gui_States
global Data

set(gui_Tr.figure_Im, 'CData', uint8(repmat(gui_States.I,[1 1 3])))
if isfield(Data , 'Forward') || isfield(Data , 'Backward')
    % takes care of all the plot handles
    update_Plot_Body();
    
    % sets up the adaptive axis
    if  gui_States.crop
        if Data.frame_Tracked((Data.frame_Index == file.range(2))) == 3
            axis(gui_Tr.figure, [ ...
                max(1,-50+ min([Data.Forward.pose(:,1,(Data.frame_Index == file.range(2)));...
                Data.Backward.pose(:,1,(Data.frame_Index == file.range(2)))]))...
                min(file.dimensions(2),50+ max([Data.Forward.pose(:,1,(Data.frame_Index == file.range(2)));...
                Data.Backward.pose(:,1,(Data.frame_Index == file.range(2)))]))...
                max(1,-50+min([Data.Forward.pose(:,2,(Data.frame_Index == file.range(2)));...
                Data.Backward.pose(:,2,(Data.frame_Index == file.range(2)))]))...
                min(file.dimensions(4),50+max([Data.Forward.pose(:,2,(Data.frame_Index == file.range(2)));...
                Data.Backward.pose(:,2,(Data.frame_Index == file.range(2)))]))])
            
        elseif Data.frame_Tracked((Data.frame_Index == file.range(2))) == 1
            axis(gui_Tr.figure, [ ...
                max(1,-50+ min(Data.Forward.pose(:,1,(Data.frame_Index == file.range(2)))))...
                min(file.dimensions(2),50+max(Data.Forward.pose(:,1,(Data.frame_Index == file.range(2))))) ...
                max(1,-50+min(Data.Forward.pose(:,2,(Data.frame_Index == file.range(2)))))...
                min(file.dimensions(4),50+max(Data.Forward.pose(:,2,(Data.frame_Index == file.range(2)))))])
            
        elseif Data.frame_Tracked((Data.frame_Index == file.range(2))) == 2
            axis(gui_Tr.figure, [ ...
                max(1,-50+ min(Data.Backward.pose(:,1,(Data.frame_Index == file.range(2)))))...
                min(file.dimensions(2),50+max(Data.Backward.pose(:,1,(Data.frame_Index == file.range(2))))) ...
                max(1,-50+min(Data.Backward.pose(:,2,(Data.frame_Index == file.range(2)))))...
                min(file.dimensions(4),50+max(Data.Backward.pose(:,2,(Data.frame_Index == file.range(2)))))])
        end
        
    end
end

% traditional update of buffer
drawnow()
end